# Generated by Django 3.1.4 on 2020-12-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_l', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(max_length=150, verbose_name='Nombre del pais')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Unidad de medida')),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_carga', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código', max_length=150, null=True, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(help_text='Nombre', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Cantidad', max_digits=10, null=True)),
                ('disponible', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Cantidad disponible', max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='PRECIO NETO', max_digits=10, null=True)),
                ('precio_lista', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='PRECIO LISTA', max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Descuento', max_digits=10, null=True)),
                ('aumento', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Aumento', max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Iva', max_digits=10, null=True)),
                ('flete', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Flete', max_digits=10, null=True)),
                ('ganancia', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Ganancia', max_digits=10, null=True)),
                ('unidad_de_medida', models.ForeignKey(help_text='Unidad de medida', on_delete=django.db.models.deletion.CASCADE, to='entidad.unidad_medida')),
            ],
        ),
    ]
