# Generated by Django 3.1.4 on 2021-01-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.RemoveField(
            model_name='unidad_medida',
            name='formula',
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
