# Generated by Django 3.1.5 on 2021-02-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_auto_20210108_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('autonumerico', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='% Gancia', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='cp',
            field=models.CharField(max_length=50, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de carga', verbose_name='Fecha')),
                ('numero1', models.CharField(default='00001', help_text='Numero', max_length=5)),
                ('numero', models.CharField(max_length=15)),
                ('sutbtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articulo', to='entidad.articulo')),
                ('cliente', models.ForeignKey(default='1', help_text='N° de documento o CUIT del tercero', limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, to='entidad.persona')),
                ('tipo', models.ForeignKey(help_text='Tipo de movimiento', on_delete=django.db.models.deletion.CASCADE, to='entidad.tipomovimiento', verbose_name='Tipo de movimiento')),
            ],
        ),
    ]
