# Generated by Django 3.1.5 on 2021-02-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0003_auto_20210201_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.categoria'),
        ),
    ]
