# Generated by Django 3.1.5 on 2021-04-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0004_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='aumento',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='disponible',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='flete',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_lista',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.unidad_medida'),
        ),
    ]
