# Generated by Django 3.1.5 on 2021-04-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0005_auto_20210408_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.TextField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
