# Generated by Django 3.1.5 on 2021-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0006_auto_20210408_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_carga',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
