# Generated by Django 3.1.5 on 2021-04-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0007_auto_20210408_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
