# Generated by Django 3.1.5 on 2021-04-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0009_auto_20210412_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
